### ISSUE TITLE
Fix adding comma in a Task/Reminder

### ISSUE THREAD

**Issue by ahmad-511** [fgr101/QB_ChatBot#1]
https://github.com/fgr101/QB_ChatBot/blob/7af26bc1f8c748b227594f95777ff9498622d95f/CHATBOT.BAS#L598
https://github.com/fgr101/QB_ChatBot/blob/7af26bc1f8c748b227594f95777ff9498622d95f/CHATBOT.BAS#L736

Hello, I heard that you're having an issue including a comma when writing a Task/Reminder.
I commented on your video but it doesn't appear for some reasons, so I thought maybe it's better to create an Issue here.

Just try to use `LINE INPUT` instead of `INPUT` instruction,

Regarding the error you've got when adding a comma is because `INPUT` can be used to accept multiple data input in one line
```basic
INPUT a,b
print a, b
``` 

Regards

**Comment by fgr101** [comment]
Hi! Thanks so much! Yes, I saw a comment in the video but wasn't able to read it either, I just don't know why. Thanks for the help, I'll try to apply your suggestions. Thanks so much. Feel free to help me with the project whenever you want!

UPDATE: I've solved the problem!! Thank you!! and now the issue with REDO FROM START when adding commas has been solved, no more problems with commas in the whole program. I'll talk about it in the next video, thank you very much for your help.

**Comment by ahmad-511** [comment]
YouTube put some comments in a place where the channel's admin is required to review before it appears for the public.

I'm happy that you fixed it,

**Comment by fgr101** [comment]
Tell me your name please, so I can give you the right credits in the next video, for your help and as a contributor in this small project. And tell me where are you from as well, thanks!

**Comment by ahmad-511** [comment]
My name is Ahmad and I am from Syria,
You really don't have to mention me, I really enjoyed your video and I was happy I could help.
Regards.
